### ISSUE TITLE
Userstory: Bedarf view benutzer

### ISSUE THREAD

**Issue by dikkadev** [Sett17/softeng2-self-service-frontend#13]
Ich als user möchte:

Alle meine aktuellen VM und deren infos kompakt sehen.
Alle meine Anträge und deren status/infos kompakt sehen.

Wir als Team werden das so umsetzen:

Wir fragen die aktuellen VMs ab und zeigen alle als karten auf dem Layout, mit hilfe von HTML-Templates.
Wir fragen die Anträge an und zeigen alle als karten auf dem Layout, mit hilfe von HTML-Templates.

**Comment by waldzwoelf** [comment]
Planning Poker: 3
