### ISSUE TITLE
Retro-Maßnahme:  Einführung regelmäßiger Sprinttermine

### ISSUE THREAD

**Issue by dikkadev** [Sett17/softeng2-self-service-frontend#15]

**Comment by Sett17** [comment]
einer muss sich assignen und sich drum kümmern

**Comment by dikkadev** [comment]
Bleiben erstmal bei 1x die Woche am Montag um 10:30.
Wenn wir bemerken das wir so viel arbeiten das wir 2x mal brauchen, dann denken wir uns noch eine Termin aus.
