### ISSUE TITLE
Userstory: passwort vergessen

### ISSUE THREAD

**Issue by dikkadev** [Sett17/softeng2-self-service-frontend#17]
ich als user moechte:
einen knopf habe ueber dem ich mir per email das passwort zurücksetzen kann.

umsetzen:
Wir geben einen knopf, und sagen den backend bescheid falls der user das moechte.

**Comment by waldzwoelf** [comment]
Planning Poker: 1

**Comment by alexandreJG** [comment]
Knopf hinzugefügt. Logik stimmt noch nicht (fragt nach Eingabe von Email und Passwort um Knopf zu betätigen)

**Comment by waldzwoelf** [comment]
Keine Funktionalität vom Backend zur Verfügung gestellt
