### ISSUE TITLE
Automatismus für das Deployment <fertig ausfüllen>

### ISSUE THREAD

**Issue by waldzwoelf** [Sett17/softeng2-self-service-frontend#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by waldzwoelf** [comment]
Planning Poker: 1

**Comment by dikkadev** [comment]
resolved in 88d98a52649b284fd5397f93f070639a2d14f80f

**Comment by dikkadev** [comment]
Imports SSH Key as GitHub secret, and uses [rsync](https://linux.die.net/man/1/rsync) um die datein rüber zu schieben
