### ISSUE TITLE
Userstory: Provisioning API Integration

### ISSUE THREAD

**Issue by waldzwoelf** [Sett17/softeng2-self-service-frontend#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by dikkadev** [comment]
#19

**Comment by waldzwoelf** [comment]
Planning Poker: 8

**Comment by dikkadev** [comment]
viel glück, werdet ihr brauchen 🍀

**Comment by dikkadev** [comment]
for example on how to use the existing js, see here
https://github.com/Sett17/softeng2-self-service-frontend/blob/706af08baa41c2b7788e3c3fc639fe5b1dcc67cb/js/vacation.js#L39

has to be remade for your api of course
